name: neuneed
author: neuneed
baseurl: 
description:  one more thing.
github: https://www.github.com/neuneed
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: neuneed@gmail.com
encoding: utf-8
language: zh-CN

##Make sure to edit the above fields, especially for disqus.

highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
